name: 'Resue other workflow'
on: [workflow_dispatch]


jobs:
  call-workflow:
    uses: ./.github/workflows/resuable.yml
    with:
      who-to-greet: '@deebify'
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo " Time was ${{ needs.call-worklfow.outputs.current-time }}"
